project_id = "dsehaqdqnrkjrhbvkfrk"

[functions.cloudflare-analytics]
verify_jwt = true

[functions.ai-domain-suggestions]
verify_jwt = true

[functions.namecheap-domains]
verify_jwt = true

[functions.cloudflare-integration]
verify_jwt = true

[functions.cpanel-integration]
verify_jwt = true

[functions.purchase-domains]
verify_jwt = true
