[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["node"]

[[build.nixpacksPlan.phases.setup]]
nixPkgs = ["nodejs_18"]

[[build.nixpacksPlan.phases.install]]
cmds = ["npm install"]

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
